version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.0
    hostname: zookeeper
    ports:
      - "2181:2181"
    expose:
      - "2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:5.2.0
    restart: unless-stopped
    depends_on:
      - zookeeper
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # Druid container
  druid:
    build:
      context: .
      dockerfile: ./dockerfiles/druid/Dockerfile
    container_name: druid
    ports:
      - 8081:8081
      - 8082:8082
      - 8083:8083
      - 8888:8888
      - 8090:8090
    depends_on:
      - kafka

  # Superset container
  superset:
    image: amancevice/superset:0.18.5
    container_name: superset
    ports:
      - 8088:8088

  jupyter:
    build:
      context: .
      dockerfile: ./dockerfiles/jupyter/Dockerfile
    volumes:
      - ./notebooks:/notebooks
    ports:
      - "3333:3333"
    command: sh /jupyter_run.sh
    restart: unless-stopped
