version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.0
    hostname: zookeeper
    ports:
      - "2181:2181"
    expose:
      - "2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:5.2.0
    restart: unless-stopped
    depends_on:
      - zookeeper
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # Divolte container
  divolte:
    image: divolte/divolte-collector
    container_name: divolte
    environment:
      - DIVOLTE_KAFKA_BROKER_LIST=kafka:29092
    volumes:
      - ./conf/divolte/:/opt/divolte/divolte-collector/conf/
    ports:
      - 8290:8290
    depends_on:
      - kafka

  # Druid container
  druid:
    image: fokkodriesprong/docker-druid
    container_name: druid
    ports:
      - 8081:8081
      - 8082:8082
      - 8888:8888
    depends_on:
      - kafka

  # Superset container
  superset:
    image: amancevice/superset:0.18.5
    container_name: superset
    ports:
      - 8088:8088

  # Superset container
  app:
    build: app/
    container_name: app
    ports:
      - 8090:8090
